from loss_functions.loss import Loss
from loss_functions.fe_loss import FiniteElementLoss
from loss_functions.thermal_2D_fe import ThermalLoss2D
from loss_functions.thermal_3D_fe import ThermalLoss3D
from loss_functions.mechanical_2D_fe import MechanicalLoss2D
from loss_functions.mechanical_3D_fe import MechanicalLoss3D